services:
  checksolution:
    image: checksolution
    build:
      context: ./checkSolution
      dockerfile: Dockerfile
    ports:
      - "8089:8089" # Проброс порта наружу
    restart: unless-stopped